### ISSUE TITLE
--nosr doesn't work

### ISSUE THREAD

**Issue by Yutang-ETH** [schneebergerlab/syri#116]
Hi SyRI,

Thank you very much for making SyRI. I was trying not to call SR with --nosr but I got this error: local_variation - ERROR - synOut.txt is not present in the directory. Exiting

If I don't add --nodr, SyRI doesn't complain at all. What could be wrong for me?

Here is my command line for SyRI:
/path/syri -c mysyri/chr1.filtered.coords -d mysyri/chr1.filtered.delta --nc 30 --nosr --prefix chr1_ -r h1_chr1.fa -q h2_chr1.fa 

Could you help check what went wrong? Thank you very much.

Best wishes,
Yutang

**Comment by mnshgl0110** [comment]
```--nosr``` can be used to skip SR identification when that step has already been done and the intermediate files generated are still present.
If the output of SR identification step is not present (either because that step was not run or it didn't or the intermediate files were deleted) then the ```--nosr``` option would not work as it cannot find the required files.
To use it, you would need to first run syri without ```--nosr``` and with the ```-k``` option.

**Comment by Yutang-ETH** [comment]
I see, thank you very much for your explanation.

Best wishes,
Yutang
