### ISSUE TITLE
SNP number is smaller

### ISSUE THREAD

**Issue by liufuyan2016** [schneebergerlab/syri#12]
When I use syri, the error is below:
all stack:
  File "/share/nas1/liufuyan/HELP/Soft/syri-master/syri/bin/syri", line 179, in <module>
    getTSV(args.dir, args.prefix, args.ref.name)
Message: '/share/nas1/liufuyan/HELP/JieCai/01.MuMer/snps.txt cannot be opened. Cannot output SNPs and short indels.'

but produced one file snps_GARB.txt. I make statistics for the file ,and the SNPnum is only 2433 ,very small ! Could you help for me to find the problems?Thank you!

**Comment by mnshgl0110** [comment]
Hi. It seems that there are two issues. First is that the program is crashing. And second is that too few SNPs were identified.
The first issue seems to be a bug. Can you please share the log file so that I could have more information about the run?
For the second issue, can you please check how many SNPs are identified when using the `show-snps` utility from MUMmer? SyRI can only report SNPs which are identified by the MUMmer alignments. So, it would be worthwhile to first check whether are indeed SNPs present in the alignments or not. Additionally, please also upload the snps_GARB.txt file.

**Comment by liufuyan2016** [comment]
show-snps produce 17107349。 The syri.log is blank.

**Comment by liufuyan2016** [comment]
The snps_GARB.txt file. I sent to your email

**Comment by mnshgl0110** [comment]
There was a bug affecting SNP identification. It should be fixed now and you should be getting proper number of SNPs.
