### ISSUE TITLE
'Pandas' object has no attribute 'to_string'

### ISSUE THREAD

**Issue by chklopp** [schneebergerlab/syri#124]
I've run syri from a conda environment.
The output files seem to be correctly produced :
- invOut.txt
- TLOut.txt
- invTLOut.txt
- dupOut.txt
- invDupOut.txt
- ctxOut.txt
- synOut.txt
- sv.txt
- notAligned.txt
- snps.txt

But then syri crashes with the following error

syri -c chr.sam -r refgenome.chr -q qrygenome.chr -k -F S
getTSV - ERROR - Error in finding parent for SV
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.7.10/envs/syri-v1.3_env/bin/syri", line 269, in <module>
    getTSV(args.dir, args.prefix, args.ref.name)
  File "syri/pyxFiles/writeout.pyx", line 152, in syri.writeout.getTSV
AttributeError: 'Pandas' object has no attribute 'to_string'

What could I change in my command line?
Or is there a solution to finish the process from here?

**Comment by mnshgl0110** [comment]
Hi Christophe,

Did you install syri using conda or manually from github? My first guess is that this is happening because of something weird happening with pandas. Try reinstalling syri in a fresh environment as that can solve the issue.

If that does not work, then could you please let me know what version of syri and pandas are you using. Also please run syri with the --log DEBUG and share the syri.log file.

Best
Manish

**Comment by chklopp** [comment]
In fact my question has been answered in the https://github.com/schneebergerlab/syri/issues/38 issue.
