### ISSUE TITLE
 SAM reader - ERROR 

### ISSUE THREAD

**Issue by Xinxin0314** [schneebergerlab/syri#126]
Hi @mnshgl0110，

When i run "nohup python3 /md1200/miniconda3/envs/syri/bin/syri -c ~/sv/minimap2/mn_zdd.sam -r ~/sv/minimap2/mn.genome.fa -q ~/sv/minimap2/zdd.genome.v1.fa -k -F S &", 
syri.log wrote that
"2022-03-21 11:37:32,929 - Reading Coords - INFO - syri:116 - Reading input from SAM file
2022-03-21 11:37:48,467 - SAM reader - ERROR - syri:116 - Error in reading SAM file: list index out of range".

I don't know why. And the same procedure is ok in another server.

Looking forward to your reply, thank you.

Best,
Xinxin

**Comment by mnshgl0110** [comment]
Hi Xinxin,

Since, it is working on another server, I think the issue could be with the python environment. Maybe try reinstalling syri in a clean environment as that can solve the issue.

If that does not work, then could you please also share the error message that you would have got in the terminal? Is this happening with a specific sam file or all sam files? What are the versions of pysam in the different servers (the one where it is working vs the one where it is not)?

Best
Manish

**Comment by Xinxin0314** [comment]
Hi mnshgl0110，

Thanks for your response. 

The syri i installed by two steps: conda-search and conda install syri=1.5.4. Two servers are same. 

The terminal information:
(syri) hyli 10:05:22 ~/pxx/sv/syri/zyd6_sn14
$ nohup python3 /md1200/hyli/miniconda3/envs/syri/bin/syri -c ~/pxx/sv/minimap2/zyd6_sn14.sam -r ~/pxx/sv/minimap2zdd0006.genome.v1.fa -q sn14.genome.fa -k -F S &
[1] 39903
(syri) hyli 10:05:44 ~/pxx/sv/syri/zyd6_sn14
$ nohup: 忽略输入并把输出追加到'nohup.out'

[1]+  退出 2                nohup python3 /md1200/hyli/miniconda3/envs/syri/bin/syri -c ~/pxx/sv/minimap2/zyd6_sn14.sam -r ~/pxx/sv/minimap2zdd0006.genome.v1.fa -q sn14.genome.fa -k -F S

The error happened in all sam files.

I checked two servers. The versions of python and pysam are the same. But the sources of syri are different, maybe that made a difference?
work server
pysam                     0.18.0           py39h5030a8b_2    bioconda
python                    3.9.10          h85951f9_2_cpython    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
no-work server
pysam                     0.18.0           py39h5030a8b_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda
python                    3.9.10          h85951f9_2_cpython    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge

----------------
Just now, I move the sam file in work server to no-work server, and it run ok. Then I run my old sam file in no-work server, it's ok ! But I run another sam files, it still made the same mistakes.
Now, I'm very confused.

Sincerely,
Xinxin

**Comment by mnshgl0110** [comment]
Hi Xinxin,

Thanks for checking. From what I understand, the issue is not reproducible. Generally, if there is an issue at the software level then it is reproducible. This again suggests that the issue could be happening either with the environment or with the server. Unfortunately, it is not possible for me to figure out the exact reason for the crash if I cannot reproduce it.

Nevertheless, could you please share the nohup.out file from the working server output and the non-working server output. The terminal output you shared now do not have the actual error message so it does not help much.

Best
Manish
