### ISSUE TITLE
How is the super large INV defined/formed ?

### ISSUE THREAD

**Issue by jxlabWzZ** [schneebergerlab/syri#137]
hi, sir
Thank you for providing an excellent SV detection software. However, I have problems with SV detection for large SVs, especially for >1Mb INV. Because i find that the alignment region in *.filtered.coords are very fragmented.

for example:
syri identified a large inv : chrY    29220000        40054179        chrY    34889612        44124518        INV     INV     10834179

*.filtered.coords:
![截屏2022-04-23 上午10 23 58](https://user-images.githubusercontent.com/54127791/164866010-4c524e8d-2397-4c05-9412-99a164583c01.png)

**Comment by mnshgl0110** [comment]
I am not sure I understand what is the issue here, but I assume it is related to large gaps in inversions. I have recently added a parameter to control that https://github.com/schneebergerlab/syri/commit/f70300bc5913f18ac77b8da88df3e4d2518a7f5d . Maybe you can try this (by downloading and installing syri from GitHub).

If this is not what you were asking, then could you please provide more information about what is the issue.

**Comment by jxlabWzZ** [comment]
Thank you for your reply. I would like to ask why there is a MB-level of structural variation, while mummer only report SYN blocks of several hundred KB at most.

**Comment by mnshgl0110** [comment]
MUMmer (nucmer) reports alignments between genomes. The alignments can break if there is significant local sequence divergence. Syri tries to identify large rearrangements spanning these local sequence divergence and can therefore identify >MB long structural rearrangements.

**Comment by jxlabWzZ** [comment]
I got it, thank you very much.
