### ISSUE TITLE
Inverted chromosome warning

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/syri#189]
https://github.com/schneebergerlab/syri/issues/184#issuecomment-1511615524

**Comment by mnshgl0110** [comment]
@InfiniteLaugh You need to ensure that for homologous chromosomes same strands are present in the assembly files. You can check the dotplots (generated by fixchr) to decide whether the cleaned chromosomes corresponds to same strands. If you are confident that same strands are being compared, then you can ignore the warning.

**Comment by InfiniteLaugh** [comment]
> @InfiniteLaugh You need to ensure that for homologous chromosomes same strands are present in the assembly files. You can check the dotplots (generated by fixchr) to decide whether the cleaned chromosomes corresponds to same strands. If you are confident that same strands are being compared, then you can ignore the warning. If using the output of fixchr, you would need to realign the genomes generated by fixchr.

Thank you for your immediate answer! ^_^
I looked through newly create file `qry.filtered.fa` & `ref.filtered.fa` , and found those warning Chromosome were successfully reversed by `fixchr`. As you have mentioned, if I try to use fixchr output to call SV, etc., do I have to run mummer again with new fasta files? Or just use the newly  produced fasta file with original `108.THrd.coords` file? Because I merely found any differences between `homologous_strand_corrected_alignments.txt` and the original `108.THrd.coords` file produced by mummer.

**Comment by mnshgl0110** [comment]
> As you have mentioned, if I try to use fixchr output to call SV, etc., do I have to run mummer again with new fasta files? 

Yes, you need to rerun alignments otherwise the genomes and alignments would not match.

**Comment by mnshgl0110** [comment]
Great that it is working. Please start a new issue for other questions.
