### ISSUE TITLE
runtime

### ISSUE THREAD

**Issue by iamTad** [schneebergerlab/syri#23]
Hi,

It's mentioned that the runtime and memory use for syri increases with the number of duplications and translocations. I have an issue in that there are major discrepancies between 2 of my runs. They're both runs comprising only 1 chromosome, each of which are around 30Mb with similar numbers of inversions. However, one run took approximately 3 hours (run A) to complete whereas the other one (run B) has taken 2 days (and is still running). Is there a something that I might be missing?

Based on mummer plots, the runA comparison has a 10Mb inversion in the middle of the chromosome while runB has a 20Mb inversion in the middle of the chromosome.

Thanks in advance!

**Comment by mnshgl0110** [comment]
Hi,
No, this is not something totally unexpected. SyRI tries to compare different combinations in which alignments can be selected to represent rearrangements. So, if a large rearrangement is represented by many small alignments, then the number of combinations increases, increasing the runtime. What affects runtime is not the number of duplications/translocations but the number of alignments describing them. Allowing larger gaps while doing whole-genome alignment, could provide few longer alignments solving this issue.
That being said, from the mummerplot, do these regions look like 'inversions' (regions inverted at their own loci) or 'inverted translocations/duplication' (inverted and relocated to a different loci)? I ask this because, the function for finding inversions was recently optimised, so if you are using the newer version of SyRI and the region is indeed an inversion, then this problem should not be there. However, the function for finding translocations and duplications is still slow for these cases. Would it be possible to share the syri.log file to see which step is taking longer?

**Comment by iamTad** [comment]
Thanks for the quick reply! The info is certainly useful. I've attached the log files (thankfully, runB as finished some time overnight). I've attached the log files and, for your reference the mummerplots.

RunA
![image](https://user-images.githubusercontent.com/6754728/74680784-87873f80-5176-11ea-8d87-6de4f30eeb07.png)

RunB
![image](https://user-images.githubusercontent.com/6754728/74680765-7a6a5080-5176-11ea-898f-86fb74fbea34.png)

[syri_runA.log](https://github.com/schneebergerlab/syri/files/4215741/syri_runA.log)
[syri_runB.log](https://github.com/schneebergerlab/syri/files/4215742/syri_runB.log)

**Comment by mnshgl0110** [comment]
Hi! Thanks for sharing the log files and the mummerplots. SyRI is indeed taking time in identifying inversions. I did not expect that as function for inversion identification should be quite fast now. But, it seems that it would need to be optimised further.

**Comment by iamTad** [comment]
No problem. At least I know the software is running properly. If only I worked on yeast or something similar! Best of luck with optimizing the software (if you plan on going that route).
