### ISSUE TITLE
How long does it take to generate the result file?

### ISSUE THREAD

**Issue by Eika728** [schneebergerlab/syri#238]
Syri has been stuck on generating the output table for 4 days, and I want to ask if this is normal. The size of my out.filtered.delta is 85M.
![image](https://github.com/schneebergerlab/syri/assets/139523735/a7b262cf-5365-4205-b31f-301f1d961ec6)

**Comment by mnshgl0110** [comment]
No, this is not normal. Can you share the current log file? If it did not take too long to reach the 'generating table output ' step, then can you rerun syri with log level debug and then share the log file as well.

**Comment by Eika728** [comment]
> No, this is not normal. Can you share the current log file? If it did not take too long to reach the 'generating table output ' step, then can you rerun syri with log level debug and then share the log file as well.

It's weird, it finally ran the results correctly on the night of the 12th. I guess it may be because the input file was too large, which resulted in a long running time? I ran another execution with a smaller input file before, and it only took three hours to generate the result file.
![image](https://github.com/schneebergerlab/syri/assets/139523735/3b03ee3a-1c74-4293-8c38-df86b998e4d4)

**Comment by mnshgl0110** [comment]
For very complex (rearranged with multiple TEs) genomes, syri can take some time but even then `Generating table output` should not take so long. Are you working with large genomes that are quite diverged (have multiple SNPs and indels)?
Nevertheless, good that it finished successfully. If possible, can you run syri on the large dataset with log-level debug and then share the syri.log file? It would help my in finding the bottleneck. NOTE: if rerunning syri, then do that in a different folder so that the current output do not get overwritten.
