### ISSUE TITLE
A very strange result of syri

### ISSUE THREAD

**Issue by majssssa** [schneebergerlab/syri#263]
I used Syri to compare the two haplotypes，and the alignment method was minimap. However, the results show that there are very few Syntenic regions, and most of them are Inverted regions and Translocated regions. This is rare in plants. So I want to know if there's something wrong with my choice of alignment method. Here's how I visualized the results using plostr.
![output_plot](https://github.com/user-attachments/assets/1a6dd422-5f4f-4843-8bb2-5c09dfd0fe1d)

**Comment by majssssa** [comment]
This is mine hic heatmap
[contact_map_Change.pdf](https://github.com/user-attachments/files/16690406/contact_map_Change.pdf)

**Comment by mnshgl0110** [comment]
There can be multiple explanations for these results. You can check for:
1) Assembly errors: do the large inversions consist of single contigs which could be mis-assembled?
2) Alignment issues: are putative syntenic regions too diverged to be aligned? Or are there many small alignments between repetitive regions resulting in large number of translocations/duplications? What effects does changing the alignment parameters have?
3) Syri filtering: By default, syri filters out low quality alignment. Does using all alignments (parameter `-f`) finds more synteny?
4) Visual artifacts: In chromosomes this big, multiple tiny translocations/duplications could give the impression that most of the genome is rearranged. What happens if you change the minimum size for a translocation/duplication to be plotted?

If everything looks OK, then these differences could indeed be real. It is possible that the chromosomes are so large because of high TE content which can in turn result in high proportion of SRs between the two haplotypes.
