### ISSUE TITLE
IndexError: Out of bounds on buffer access (axis 0)

### ISSUE THREAD

**Issue by pan-genome** [schneebergerlab/syri#29]
any idea what could go wrong? Thanks

python3 /path/path/syri/syri/bin/syri -c d3-filter-1511.coords -r /path/path/projects/sv/canola/ref.fa -q /path/path/projects/sv/canola/query.fa -k --log DEBUG -d d3-filter-1511.delta

Namespace(TransUniCount=1000, TransUniPercent=0.5, all=False, bruteRunTime=60, chrmatch=False, cigar=False, delta=<_io.TextIOWrapper name='d3-filter-1511.delta' mode='r' encoding='UTF-8'>, dir=None, fout='syri', ftype='T', increaseBy=1000, infile=<_io.TextIOWrapper name='d3-filter-1511.coords' mode='r' encoding='UTF-8'>, keep=True, log='DEBUG', log_fin=<_io.TextIOWrapper name='syri.log' mode='w' encoding='UTF-8'>, nCores=1, nosnp=False, nosr=False, nosv=False, novcf=False, offset=5, prefix='', qry=<_io.TextIOWrapper name='/path/path/projects/sv/canola/query.fa' mode='r' encoding='UTF-8'>, ref=<_io.TextIOWrapper name='/path/path/projects/sv/canola/ref.fa' mode='r' encoding='UTF-8'>, seed=1, sspath='show-snps')
syri - WARNING - starting
('Cluster is too big for Brute Force\nTime taken for last iteration ', 5.7220458984375e-05, ' iterations remaining ', 36)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 9.870529174804688e-05, ' iterations remaining ', 38)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/path/path/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/path/path/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 373, in syri.pyxFiles.synsearchFunctions.syri
  File "syri/pyxFiles/inversions.pyx", line 729, in syri.inversions.getInversions
  File "syri/pyxFiles/inversions.pyx", line 290, in syri.inversions.getProfitable
IndexError: Out of bounds on buffer access (axis 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/path/syri/syri/bin/syri", line 115, in <module>
    chrlink = startSyri(args)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 311, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 312, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/path/path/anaconda3/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/path/path/anaconda3/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
IndexError: Out of bounds on buffer access (axis 0)

**Comment by mnshgl0110** [comment]
Hi. It is difficult to say what exactly caused this error from the error message. Would it be possible to share the syri.log file? Also, sample input files which are resulting in this error would be great.
SyRI was designed using python 3.5.6 with pandas version 0.23.4. Newer versions of pandas sometimes result in such errors. Could you please try running syri with the suggested python/pandas version?

**Comment by song984888** [comment]
> Hi. It is difficult to say what exactly caused this error from the error message. Would it be possible to share the syri.log file? Also, sample input files which are resulting in this error would be great.
> SyRI was designed using python 3.5.6 with pandas version 0.23.4. Newer versions of pandas sometimes result in such errors. Could you please try running syri with the suggested python/pandas version?

hi, thank you for your suggestion.
i run the example dataset and it's OK.
but using my dataset, it could not be finished and still cause same error. some of chromosomes have results.
this is the syri.log with DEGUG:
[syri.log](https://github.com/schneebergerlab/syri/files/4484170/syri.log)
[run.log](https://github.com/schneebergerlab/syri/files/4484173/run.log)

**Comment by mnshgl0110** [comment]
Hi. Thanks for sharing the files.
The example dataset is a minimalistic example to check whether SyRI is installed correctly and to demonstrate how to use it. It does not test for all use cases. So, it is still possible that your issue is happening because of the unsuitable environment.
Also, from the syri.log, I see that there are only two forward alignments between homologous chromosome 3 (2020-04-15 23:57:49,293 — syri.chr3 — INFO — mapstar:44 — chr3 (2, 11)). Similarly, some other chromosomes too have very few forward alignments. This could mean that different strands are being considered in the two assemblies (which result in mostly inverted alignments). SyRI requires that same strands of homologous chromosomes are compared, and could result in such errors if that is not the case. I suggest you to check the alignments and reverse complement the chromosomes for which different strands are present in the two assemblies. Alternatively, you can use the latest version of SyRI, which would provide a warning message if there are too many inverted alignments between homologous chromosomes. But still, you would need to reverse complement them manually.

**Comment by pan-genome** [comment]
Thank you mnshgl0110! I set up syri on an EC2 using python 3.5.6 with pandas version 0.23.4 and the scripts finished without error this time.

**Comment by mnshgl0110** [comment]
Good to know that.
Best.
