### ISSUE TITLE
no insertion or deletion

### ISSUE THREAD

**Issue by ersgupta** [schneebergerlab/syri#37]
I am running syri to get rearrangements between two genomes but I do not get any insertion or deletions as output. Is it supposed to be like this? or does it have to be enabled in some way?

```
python3 /apps/syri-1.2/syri/bin/syri -c test.sam -r ref.fa -q query.fa -k -F S --prefix syri.all --nc 4
```
Thanks

**Comment by mnshgl0110** [comment]
Hi Saurabh. SyRI finds indels by default so they should be there in the output. Have you tried performing the [example analysis](https://schneebergerlab.github.io/syri/pipeline.html)? If you are not getting indels with the example data as well, then there could be some issues with the SyRI installation. Otherwise, there might be something unexpected happening when analysing alignments in test.sam.
Also, please check that you are not using pandas version 0.24 as it can cause issues.
In any case, it would be helpful if you run SyRI with the `DEBUG` log setting and share the syri.log file.
