### ISSUE TITLE
result interpretation

### ISSUE THREAD

**Issue by liu3zhenlab** [schneebergerlab/syri#40]
Thanks the syri team. This is a very nice tool. I have several questions to interpret the output.

1. Are CPG and CPL local duplicated? What is the major difference between CPG/L and Duplication gain/loss?

3. Can we consider Insertion/Deletion as presence/absence variation (PAV)?

4. I guess I am confused about the difference between Insertion/Deletion and CPG/CPL too.

thank you,

-Sanzhen

**Comment by mnshgl0110** [comment]
1. SyRI first identifies all syntenic regions followed by rearranged (inverted, translocated, duplicated) regions. Then it identifies local sequence variations like CPG/CPL in all these syntenic and rearranged regions. So, CPG/CPL are different from Duplications in that duplications result in a break in genomic synteny. Consequetively, it is also possible that a larger duplicated region has local CPG/CPL regions within it.

2. That is difficult to say as it would depend on the broader scope of the study and what regions are being considered. A deletion in a region which is only syntenic is a PAV, but a deletion in a region that is duplicated in the query genome (has two copies), of which only one has the deletion, may not be a PAV. So, you would need to decide based on the goals of your analysis. In case you have not noticed yet, `not aligned' regions can also be considered as PAV.

3. SyRI identifies InDels from (a) alignments between genomes (b) conformation of alignments in syntenic/rearranged regions (Figure S8 from the paper). In the second case, it uses the `--allow-offset` parameter to allow for some overlap before annotating the region as CPG/CPL. This works well generally, but I can imagine it resulting in sub-optimal annotations in rare cases. You can modify the `--allow-offset` parameter to twerk this. So, in short, the difference between InDels and CPG/CPL is based on how they are defined from alignments, but this can be controlled using the `allow-offset` parameter.

**Comment by liu3zhenlab** [comment]
Hi Manish, this is very helpful. Thanks.
If I change allow-offset, will some CPG/CPL annotated as INS/DEL? Also I noticed that in many INS/DEL, column 2 is greater than column 3 in syri.out (see below for an example). What does that mean?
```
chr1	16356215	16356212	-	-	chr1	17392321	17392637	INS178	SYN329	INS	-
```

**Comment by mnshgl0110** [comment]
Yes, if you increase allow-offset, then CPG/CPL for which number of overlapped basepairs is less than allowed-offset would be annotated as InDels.

Column 2 is greater than column 3 because the alignments were overlapping (as default allowed-offset value is 5). This can be ignored, and you can assign the insertion at any one of the two position.

**Comment by liu3zhenlab** [comment]
thanks Manish.

**Comment by liu3zhenlab** [comment]
Hi Manish, sorry to bother you with another question. I am not sure the interpretation of TDM. In a TDM event, do both genomes contain TDM? Can the copy variation between two genomes be allowed for a TDM match?

**Comment by liu3zhenlab** [comment]
Hi Manish, sorry to bother you with another question. I am not sure the interpretation of TDM. In a TDM event, do both genomes contain TDM? Can the copy variation between two genomes be allowed for a TDM match?

**Comment by mnshgl0110** [comment]
TDMs annotate regions in the two genomes that correspond to overlapping alignments in both genomes (please see Figure S8 of the paper). So, in a TDM event both genomes would contain the repeated copies, and the length of the TDM region in each genome would correspond to the region which is repeated.

Yes, copy number variation can also result in TDM annotation. Imagine having three tandem copies of a region in reference and two copies in the query. This is would be a copy variation, but since the regions are in tandem and would result in overlapping alignments in both genome, SyRI would annotate such regions as TDM. I hope this helps you in understanding the output better.

**Comment by liu3zhenlab** [comment]
That is what I thought. Thanks Manish.
