### ISSUE TITLE
question about NOTAL and CNVs

### ISSUE THREAD

**Issue by shiyi-pan** [schneebergerlab/syri#54]
I confused about NOTAL and CNVs . what the difference between NOTAL and PAV and why my syri.vcf don't include CNV.Thank you very much.

**Comment by mnshgl0110** [comment]
NOTAL are non-aligning regions between two annotated structural regions. Because there is no alignment and structural information, these regions are only described as NOTAL. Though, in practice, they can be considered as novel genome specific INDELS (or PAVs).

CNVs are reported as CPG (Copy gain in non-reference genome) or CPL (Copy loss in non-reference genome) in the .vcf file. I guess, you would have those. You could also check the tsv file for copygain/copyloss variation.

More information on how SyRI classifies variation is present in the Figure 2 and Figure S8 in the SyRI paper (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1911-0)

**Comment by shiyi-pan** [comment]
ok, Thank you for your reply . I well read the paper carefully。

**Comment by mnshgl0110** [comment]
I will close the issue for now. Please feel free to re-open it if there are more questions.
