### ISSUE TITLE
Chromosome length error

### ISSUE THREAD

**Issue by jtweir** [schneebergerlab/syri#57]
Hi Manish,

For only 1 of several genome pairs run with the exact same pipeline using MUMmer 3.23 and Python 3.5, syri outputs the following error:
"ERROR - Length of reference sequence of Chr1 is less than the maximum coordinate of its aligned regions. Exiting."

I have identical chromosome numbers and names for my two genomes. I am not sure how to proceed with this error.

Best wishes

**Comment by mnshgl0110** [comment]
Hi. This means that the coordinates in the alignment (coords/sam/bam) file do not match the chromosome size in the fasta file. For example: if Chr1 in fasta is 1000bp long and there is an alignment for region Chr1:900-1010, then you would see this error. This could have resulted from manual changes in the alignment file or because of bugs in the aligner. Please check the consistency of the alignments and fasta file.
