### ISSUE TITLE
overlapping transversions

### ISSUE THREAD

**Issue by jtweir** [schneebergerlab/syri#58]
Hi Manish,

For one pair of species run through syri, I get the same 18 Mb region on a large chromosome being defined as three separate translocations (TRANS) and one duplication (DUP). They each have slightly different but non identical breakpoints near 15 Mb and 33 Mb in the genome. This results in an overestimation of the proportion of the genome in a translocated state.

Here are the overlapping entries in the out file:
ChrZ__CM019933.1_RagTag	15149884	32775603	-	-	ChrZ__CM019933.1_RagTag	47408870	64910490	TRANS1816	-	TRANS	-
ChrZ__CM019933.1_RagTag	15200529	32978349	-	-	ChrZ__CM019933.1_RagTag	47457787	65019544	TRANS1817	-	TRANS	-
ChrZ__CM019933.1_RagTag	15279688	33008922	-	-	ChrZ__CM019933.1_RagTag	47541609	65025791	TRANS1818	-	TRANS	-
ChrZ__CM019933.1_RagTag	15841307	32996058	-	-	ChrZ__CM019933.1_RagTag	48088533	65039556	DUP2220	-	DUP	copygain

I see no obvious issues in the coordinates file (see attached) output by nucmer that would suggest this region had been duplicated. Thanks for your assistance.
[CombinedGenome_m_i90_l100.coords.zip](https://github.com/schneebergerlab/syri/files/5689564/CombinedGenome_m_i90_l100.coords.zip)

**Comment by mnshgl0110** [comment]
Yes, these are indeed sub-optimal results. SyRI first finds all possible translocations and duplications (called candidate Translocations and Duplications or cTDs) in the genome and then select those cTDs that can co-exist (not completely overlapping) and give the highest alignment score for the genomes. In this specific case, it seems that the differences in breakpoints were large enough for the algorithm to consider them as separate translocations and hence it reported all of them.

Without checking the coords file in detail, I think this could have happened because of smaller rearrangements at the terminal regions of the larger translocation. If possible, please share the SyRI output including alignments as well. I would try to fix this.

For now, you can either filter the wrongly predicted translocations manually if it is in this one region only. Alternatively, you can try using minimap2. The default parameters of minimap2 are less sensitive to smaller variations and results in longer alignments which I think would filter out the noisy alignments making SyRI's predictions better.

**Comment by jtweir** [comment]
I will try minimap. I have attached the syri output file as well.
[3__syri.zip](https://github.com/schneebergerlab/syri/files/5690316/3__syri.zip)

**Comment by jtweir** [comment]
I started looking at other species pairs and I found another with a 40Mb transversion that had the same transversion, but with marginally different start and end coordinates represented three times in the output file. If you require additional files just let me know. I prefer to send via email.

**Comment by mnshgl0110** [comment]
Hi. I have modified the TD identification algorithms and this problem should be resolved now. The updated method is in [branch V1.4](https://github.com/schneebergerlab/syri/tree/V1.4) and you can test it if you want. Though, I have not yet tested it extensively for bugs, but I think there won't be any :)

Let me know if this does not work.

**Comment by mnshgl0110** [comment]
The update seems to be working without bugs and as such I think that this problem should not be there any more.

**Comment by jtweir** [comment]
I tried the new version on two different pairs that had the overlapping of transversions. The original syri works on both (and gives the overlapping error), but I get the following error for each when using the branch V1.4 syri:

Traceback (most recent call last):
  File "/home/0_PROGRAMS/syri/syri/bin/syri", line 216, in <module>
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 446, in syri.pyxFiles.synsearchFunctions.startSyri
AttributeError: 'Namespace' object has no attribute 'tdolp'

**Comment by mnshgl0110** [comment]
If you do ```python $PATH/TO/SYRI -h``` then do you see the following option in the help?
`  --tdmaxolp TDOLP      Maximum allowed overlap between two translocations.
                        Value should be in range (0,1]. (default: 0.8)
`
I guess you might be using the old SyRI executable which do not have this parameter and therefore is resulting in this error.

**Comment by jtweir** [comment]
You are correct. I am now pointing to the correct SyRE 1.4 version and it seems to have run fine. I have commitments much of today and will confirm this evening if it correctly handled the overlapping translocations.

**Comment by jtweir** [comment]
I can confirm SyRI 1.4 has worked well in the two pairs of genomes I reported where large transversions overlapped. Thanks Manish for pulling this together and so quickly!

**Comment by mnshgl0110** [comment]
Excellent. Thanks for sharing the data and letting me know that it is fixed now.
