### ISSUE TITLE
Is there any way to integration results from different alignment tools?

### ISSUE THREAD

**Issue by zhiyongli1995** [schneebergerlab/syri#62]
Hi, 
I have used syri to obtain the structural variations between two genomes with two alignment tools (i.e. minimap2 and mummer). However, I found that most variations were different from two tools.  So I have the following questions:

1. How do I choose the optimal alignment tool?
2. Is there any way to integration syri's results from different alignment tools?
3. How do I identify the truth of the variation?

Awaiting for your reply. Thank you very much!

**Comment by mnshgl0110** [comment]
Hi @zhiyongli1995,

The optimal alignment tool would depend on your specific analysis. When using default parameters, nucmer is more sensitive compared to minimap2 and could find many smaller alignments, but this increases number of noisy alignments as well and that may result in noisy annotations by SyRI. Minimap2 results in longer alignments but misses some smaller alignments, which results in cleaner annotations by SyRI but some SRs might be missed. In essence, you want to check which alignment tool results in alignment best suited for your task.

Currently, there is no way to integrate SyRI results from different runs.

I would assume that most of the differences in the variation would be in transposable elements. For non-repetitive regions, the variation should be quite similar (and close to the biological truth) irrespective of the aligner used. There could still be some differences in the breakpoints and absolute coordinates of variation because of differences in alignment algorithms though. To be sure that the predicted variation are correct, you can check the genome assemblies directly. I cannot think any of a better strategy for validating the variation. Of course, if there are errors in assembly than the predicted variation would not be true biological variation.

Best
Manish

**Comment by zhiyongli1995** [comment]
Hi @mnshgl0110,

Sorry for late reply. The species I'm analyzing are maize. I got mummer3 parameters as following codes, which were proposed in this article (Goel et al. Genome Biology, 2019).
`nucmer --maxmatch -c 500 -b 500 -l 100 refgenome qrygenome`
Is this the best parameters for maize analysis?

Best
Zhiyong

**Comment by mnshgl0110** [comment]
Hi Zhiyong, I think you can use these parameter values and expect good alignments for downstream analysis. However, it is not possible for me to say whether these would be the best set of parameter for your analysis.

**Comment by zhiyongli1995** [comment]
Hi @mnshgl0110,
Thank you for your reply. I got your point. I will continue to test these parameters or other parameters. You can close this issue and thank you again.
Best regards.
Zhiyong
