### ISSUE TITLE
Interchromosomal rearrangments

### ISSUE THREAD

**Issue by PhDstuff** [schneebergerlab/syri#7]
Hello,

Is there anyway to make this work with inter-chromosomal rearrangements?
For assemblies with an equal number of chromosomes I get this response due to a reciprocal translocation between two chromosomes

`Reading Coords — ERROR — chrVII_chrIV in genome B is best match for two chromosomes in genome A. Cannot assign chromosomes automatically.`

Thanks!

**Comment by mnshgl0110** [comment]
Ideally, in the two fasta files, sequences corresponding to the same chromosomes should have exactly same identifiers. For example:
##File1.fa
> Chr1 
ATGCGGAT
> Chr2
GTCAAGTC

##File2.fa
> Chr1
GACTATGC
> Chr2
GGTCAGGT

When there is a discrepancy in the identifiers, SyRI tries to match chromosomes in the two fasta files using their alignment information. However, sometimes it is not possible to automatically match chromosomes (like in the above case). This issue can be resolved by manually fixing the chromosome identifiers, so that corresponding chromosomes in the two fasta files have exactly the same identifiers.
