### ISSUE TITLE
Does syri also annotate DUP/INVDP or TRANS/INVTR within large INV?

### ISSUE THREAD

**Issue by cai1991** [schneebergerlab/syri#73]
Hi Manish,

I read your paper (Goel et al., Genome Biology, 2019) and it seems to me that syri annotates only local variations in syntenic and rearranged regions. Does it also annotate rearranged regions in the already annotated rearranged regions? In my data, I found TRANS/INVTR and DUP/INVDP in INVs (below figure, blue and dark violet lines represent translocations and duplications, respectively  ). Is it expected?

![INV1](https://user-images.githubusercontent.com/53818099/116300952-ca439f00-a79f-11eb-9a85-a17532bfe8c0.png)

![INV2](https://user-images.githubusercontent.com/53818099/116300968-ce6fbc80-a79f-11eb-80a9-48323f373b7a.png)

Thanks a lot in advance for your help.

Best,
Chengcheng

**Comment by mnshgl0110** [comment]
Hi Chengcheng,

If an alignment is overlapping an inversion region, then it could only be annotated as duplication and only if the other end of the alignment aligns a currently un-annotated region. 
![image](https://user-images.githubusercontent.com/16225647/116379128-0237fa00-a813-11eb-95fd-32eeec4148a8.png)

Alignments overlapping with syntenic/inversions regions are not annotated as translocations because they have more than one copy in either of the genomes.

Please let me know if there are more questions.

Best
Manish

**Comment by cai1991** [comment]
Thanks a lot Manish, that is clear.

Best,
Chengcheng
