### ISSUE TITLE
Interpreting the output

### ISSUE THREAD

**Issue by skyungyong** [schneebergerlab/syri#84]
Hi! 

I just completed running syri on two closely related species with the following commends. The reference is already at the chromosome level. The query was scaffolded based on homology with ragtag. 

```
nucmer --maxmatch -t 28 -c 500 -b 500 -l 100 SP.fasta SH.scaf.fasta
delta-filter -m -i 90 -l 100 out.delta > out_m_i90_l100.delta
show-coords -THrd out_m_i90_l100.delta > out_m_i90_l100.coords
syri -c out_m_i90_l100.coords  -d out_m_i90_l100.delta -r SP.fasta -q SH.scaf.fasta --nosnp
```
The syri output indicates that the majority of the regions are unaligned. I wasn't sure if this would be a typical output you would see or whether something is not going correctly. 

#Structural annotations
#Variation_type Count   Length_ref      Length_qry
Syntenic regions        3319    188326945       186075338
Inversions      98      71048065        69441164
Translocations  2163    19734939        19687760
Duplications (reference)        3517    15024754        -
Duplications (query)    4840    -       23942703
Not aligned (reference) 7845    636787525       -
Not aligned (query)     9644    -       610916131

Thank you for your help!

**Comment by mnshgl0110** [comment]
It is possible that the two genomes are highly diverged and therefore has mostly not aligning regions. You mentioned that you are comparing two closely related species, so it could be the case that even though they are closely related there genomes are quite different. In our [Gamete-Binning](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02235-5) paper, we showed that even the two haplotypes of a diploid organism can be very different (Fig 5). Also, in a [tetraploid potato](https://www.biorxiv.org/content/10.1101/2021.05.15.444292v1.full), we find that there are significant proportions of not aligning regions between haplotypes as well (Fig 3d). So, I would not be surprised if your results are indeed biologically correct.

Testing whether these not aligning regions are technical noise is rather straight-forward. Just check your alignments. If these regions are not aligned there then SyRI would also classify then NOTAL. You can experiment with decreasing alignment sensitivity, or try different aligners. I think you are using mummer4. I have had issues with it. Maybe you can try mummer3 or minimap2. In the end, you want to see what is the reason that these regions are not aligned. Is it only because of your aligner settings or because they are indeed different sequences.

**Comment by skyungyong** [comment]
Thank you for your suggestions. It seems like even with mummer3 and minimap2, most regions are identified to be unaligned. I will need to examine the genome and see what this means.
