### ISSUE TITLE
merge the results of multiple SVs

### ISSUE THREAD

**Issue by hexin010101** [schneebergerlab/syri#85]
I obtained multiple sets of SV vcf files by comparing them with the reference genome. Is there any way to merge these files to get a non-redundant SV set?

**Comment by mnshgl0110** [comment]
We are developing tool for this, but it is not available yet.

**Comment by hexin010101** [comment]
Great, thanks for the quick reply

**Comment by Chenglin20170390** [comment]
Hi, how about SVs merge tools ? is it avalible now ? 
Or  do you have any suggestions for merge vcf(snps and SVs)  from syri? 
Thanks.

**Comment by mnshgl0110** [comment]
We still do not have the tool for proper merging of SVs yet. However, for merging SNP/indels, you can try bcftools merge.

**Comment by Chenglin20170390** [comment]
Thanks~

**Comment by ahishsujay** [comment]
Hi! I've recently used SyRI and have ~40 VCF files I would like to merge. Would you recommend using `SURVIVOR` (https://github.com/fritzsedlazeck/SURVIVOR) in order to merge these SVs? I plan on separating SNPs and INDELs, merging them using `bcftools merge` and using `SURVIVOR` to merge the remaining SVs. 

Please let me know if you think this is a good idea, or any suggestions. 

Thanks!
