### ISSUE TITLE
Can I remove the parameter '-maxmatch'

### ISSUE THREAD

**Issue by shehongbing** [schneebergerlab/syri#99]
Hi,
   when I performed the alignment between two genomes using Nucmer. It spend long time with the parameter '-maxmatach'. So can I remove the parameter?

THX

Hongbing

**Comment by mnshgl0110** [comment]
The --maxmatch parameter allows for overlapping alignments from repeat
regions. Without it, such alignments might not be identified. As genomic
duplications are identified using overlapping alignments, removing
--maxmatch might decrease efficiency in finding duplications. If
duplications are not important, then instead of --maxmatch you can consider
using --mum to get alignments from unique regions only.
